# Generated by Django 5.0.11 on 2025-05-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rating Categories',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('number_of_places', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('addiction_types', models.ManyToManyField(blank=True, related_name='facilities_by_addiction_type', to='help_section.category')),
                ('age_gender_groups', models.ManyToManyField(blank=True, related_name='facilities_by_age_gender', to='help_section.category')),
                ('counseling_types', models.ManyToManyField(blank=True, related_name='facilities_by_counseling_type', to='help_section.category')),
                ('facility_types', models.ManyToManyField(blank=True, related_name='facilities_by_facility_type', to='help_section.category')),
                ('legal_issues', models.ManyToManyField(blank=True, related_name='facilities_by_legal_issues', to='help_section.category')),
                ('other_actions', models.ManyToManyField(blank=True, related_name='facilities_by_other_actions', to='help_section.category')),
                ('program_lengths', models.ManyToManyField(blank=True, related_name='facilities_by_program_length', to='help_section.category')),
                ('psychotherapy_types', models.ManyToManyField(blank=True, related_name='facilities_by_psychotherapy_type', to='help_section.category')),
                ('therapy_types', models.ManyToManyField(blank=True, related_name='facilities_by_therapy_type', to='help_section.category')),
                ('wojewodztwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities_by_wojewodztwo', to='help_section.category')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='help_section.facility')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='help_section.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help_section.ratingcategory')),
            ],
            options={
                'verbose_name_plural': 'Facility Ratings',
                'unique_together': {('facility', 'user', 'rating_category')},
            },
        ),
    ]
