# Generated by Django 5.0.11 on 2025-05-25 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='age_gender_groups',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='other_actions',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='counseling_types',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='psychotherapy_types',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='legal_issues',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='facility_types',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='wojewodztwo',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='addiction_types',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='program_lengths',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='therapy_types',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='facilityrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='facilityrating',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facilityrating',
            name='rating_category',
        ),
        migrations.RemoveField(
            model_name='facilityrating',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Placówka', 'verbose_name_plural': 'Placówki'},
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='address',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='number_of_places',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='slug',
        ),
        migrations.AddField(
            model_name='facility',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='hyperreal_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='RatingCategory',
        ),
        migrations.DeleteModel(
            name='FacilityRating',
        ),
    ]
