# Generated by Django 5.0.11 on 2025-05-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_section', '0002_remove_facility_age_gender_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
