# Generated by Django 5.0.11 on 2025-05-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_section', '0003_facility_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='full_address_text_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
