# Generated by Django 5.0.11 on 2025-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_section', '0004_facility_full_address_text_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='addiction_types_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='counseling_types_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_type_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='last_updated_hyperreal_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='number_of_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='other_activities_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='program_lengths_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='psychotherapy_types_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='therapy_types_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='voivodeship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
