# Generated by Django 5.0.11 on 2025-06-17 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_section', '0007_comment_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategoria Oceny',
                'verbose_name_plural': 'Kategorie Ocen',
            },
        ),
        migrations.CreateModel(
            name='FacilityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='help_section.facility')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help_section.ratingcategory')),
            ],
            options={
                'verbose_name': 'Ocena Placówki',
                'verbose_name_plural': 'Oceny Placówek',
                'unique_together': {('facility', 'author', 'category')},
            },
        ),
    ]
