# Generated by Django 5.0.11 on 2025-06-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_section', '0008_ratingcategory_facilityrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityrating',
            options={'verbose_name': 'Ocena placówki', 'verbose_name_plural': 'Oceny placówek'},
        ),
        migrations.AlterModelOptions(
            name='ratingcategory',
            options={'verbose_name': 'Kategoria oceny', 'verbose_name_plural': 'Kategorie ocen'},
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
