# Generated by Django 4.2.23 on 2025-07-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_section', '0009_alter_facilityrating_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddictionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rodzaj uzależnienia',
                'verbose_name_plural': 'Rodzaje uzależnień',
            },
        ),
        migrations.CreateModel(
            name='AdditionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Działanie dodatkowe',
                'verbose_name_plural': 'Działania dodatkowe',
            },
        ),
        migrations.CreateModel(
            name='AgeGenderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Grupa wiekowa/płeć',
                'verbose_name_plural': 'Grupy wiekowe/płci',
            },
        ),
        migrations.CreateModel(
            name='CounselingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Poradnictwo',
                'verbose_name_plural': 'Poradnictwa',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Typ placówki',
                'verbose_name_plural': 'Typy placówek',
            },
        ),
        migrations.CreateModel(
            name='LegalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kłopot z prawem',
                'verbose_name_plural': 'Kłopoty z prawem',
            },
        ),
        migrations.CreateModel(
            name='ProgramLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Długość programu',
                'verbose_name_plural': 'Długości programów',
            },
        ),
        migrations.CreateModel(
            name='PsychotherapyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Psychoterapia',
                'verbose_name_plural': 'Psychoterapie',
            },
        ),
        migrations.CreateModel(
            name='TherapyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rodzaj terapii',
                'verbose_name_plural': 'Rodzaje terapii',
            },
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Województwo',
                'verbose_name_plural': 'Województwa',
            },
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='addiction_types',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.addictiontype'),
        ),
        migrations.AddField(
            model_name='facility',
            name='age_gender_groups',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.agegendergroup'),
        ),
        migrations.AddField(
            model_name='facility',
            name='counseling_types',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.counselingtype'),
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_types',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.facilitytype'),
        ),
        migrations.AddField(
            model_name='facility',
            name='legal_issues',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.legalissue'),
        ),
        migrations.AddField(
            model_name='facility',
            name='other_actions',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.additionalactivity'),
        ),
        migrations.AddField(
            model_name='facility',
            name='program_lengths',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.programlength'),
        ),
        migrations.AddField(
            model_name='facility',
            name='psychotherapy_types',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.psychotherapytype'),
        ),
        migrations.AddField(
            model_name='facility',
            name='therapy_types',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.therapytype'),
        ),
        migrations.AddField(
            model_name='facility',
            name='voivodeships',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='help_section.voivodeship'),
        ),
    ]
