# Generated by Django 4.2.23 on 2025-07-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_section', '0010_addictiontype_additionalactivity_agegendergroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
